use_frameworks!

platform :ios, '9.0'

target 'GraphPod_Example' do
  pod 'GraphPod', :path => '../'

  target 'GraphPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
  
  target 'GraphPod_Performance_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
