# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ms-test-1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ms-test-1
  pod "GraphPod", path: '../'
  target 'ms-test-1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ms-test-1UITests' do
    # Pods for testing
  end

end
